# Project: C嗎
# Makefile created by Dev-C++ 5.15

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
RES      = C嗎_private.res
OBJ      = main.o $(RES)
LINKOBJ  = main.o $(RES)
LIBS     = -L"D:/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib32" -static-libgcc -lgraphics -luuid -lmsimg32 -lgdi32 -limm32 -lole32 -loleaut32 -lopengl32 -lglu32 -lgdi32 -lwinmm -lglut32 -lopengl32 -lglaux -lglut -lfaultrep -lfwpuclnt -lgmon -lgpapi -lgraphics -lwsock32 -luser32 -lurlmon -lwininet -ld3dx9 -ld3d9 -lsetupapi -lnetapi32 -lvfw32 -lws2_32 -lsapi -lpsapi -lwtsapi32 -liphlpapi -m32
INCS     = -I"D:/Dev-Cpp/TDM-GCC-64/include" -I"D:/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"D:/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"D:/Dev-Cpp/TDM-GCC-64/include" -I"D:/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"D:/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"D:/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = C嗎.exe
CXXFLAGS = $(CXXINCS) -O2 -m32 -lwsock32
CFLAGS   = $(INCS) -O2 -m32 -lwsock32
RM       = del /q

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

C嗎_private.res: C嗎_private.rc 
	$(WINDRES) -i C嗎_private.rc -F pe-i386 --input-format=rc -o C嗎_private.res -O coff 

